apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: team-app
type: Opaque
data:
  POSTGRES_USER: dGVhbV91c2Vy
  POSTGRES_DB: dGVhbV9hcHBfZGI=
  POSTGRES_PASSWORD: U3VwZXJTZWN1cmVQYXNzd29yZDEyMyE=
  JWT_SECRET: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfbG9jYWxfZGV2XzEyMzQ1

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: team-app
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: team-app
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
